### ISSUE TITLE
Procedure/Trigger/Function ideas

### ISSUE THREAD

**Issue by corburn** [corburn/cs345#1]
Procedure: As an employee, what is my schedule for this week?

Trigger: Set the Order/Request dispatch time to now()/the current time when a dispatcher is assigned to the order.

**Comment by jak287** [comment]
Would you be able to get on Skype this evening? Mike and I are going to
trying working on this tonight.

I'm wondering if that procedure wouldn't be better fitted as a view for the
employees. I'm going to put together a view for the customers that shows
each of their orders and a view for the restaurants that shows how many
orders have been placed from them.

**Comment by corburn** [comment]
Function:
- [x] As an employee what is my schedule for this week?
- [x] As a customer, what is the total cost for my order?

Views
- [x] Schedule view
- [x] Customer view
- [x] Restaurant view
- [x] Request view

Triggers:
- [x] Set the dispatch time to now() when a employee is assigned as the dispatcher for a request.

**Comment by MikeDeberg** [comment]
Hey guys,

I was looking at the auto insert of dispatch time on assignment of delivery
driver and came up with this:

CREATE TRIGGER dispatch_time_after_delivery_assignment
AFTER UPDATE OF CULUMN driver_id ON Request
BEGIN
UPDATE Request SET dispatch_time = CURRENT_TIMESTAMP;
END dispatch_time_after_delivery_assignment;
/

Then I began looking into the function "as a customer, what is the total
cost for my order?" but I found that it seems to require just a SUM() call
in a select statement which will require a number of join statements. Was
there another way of doing it that would necessitate an function? If so
please point me in the right direction and I will tackle it.

Thanks,
Mike

**Comment by corburn** [comment]
Nice one Mike! Without a `WHERE` clause I think the `UPDATE` will change all the rows instead of just the one that tripped the trigger. The functions, views, and triggers are just ideas so we have something to work with. This is what I have so far for the weekly schedule:

```
-- Return this weeks schdule for the given employee id.
create or replace function f_week_schedule(p_empno emp.empno%type)
    sunday Date;
    saturday Date;
    BEGIN
        SELECT TRUNC(sysdate-1, 'IW') INTO sunday FROM dual;
        SELECT TRUNC(sysdate+5, 'IW') INTO saturday FROM dual;
        SELECT * FROM schedule_view WHERE start BETWEEN sunday AND saturday;
    END;
/
```

**Comment by jak287** [comment]
The reason we decided to create a total_cost function was to remove the
need to have that same attribute in the Request table and so we could call
on the function for both Employees and Customers. It will probably be
centered around a SUM() which I think is fine. We are working to create a
view for the Request table that formats all the time and the total_cost
function would be called there. Then we can say that the function is
available for future developments on the Customer end. If you have any
thoughts on better ways to implement it or a better function to replace it,
go for it.
